using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace schlexcel.win
{
  public class Jokes
  {
    private static readonly string[] jokes = new[]
    {
      $@"Q: What does a nosey pepper do?{Environment.NewLine}A: Gets jalapeno business! ",
      $@"Q: What do you call a fake noodle?{Environment.NewLine}A: An Impasta ",
      $@"Q: What do you call an alligator in a vest?{Environment.NewLine}A: An Investigator ",
      $@"Q: What happens if you eat yeast and shoe polish?{Environment.NewLine}A: Every morning you'll rise and shine! ",
      $@"Q: ""What's the difference between a guitar and a fish?""{Environment.NewLine}A: ""You can't tuna fish."" ",
      $@"Q: Did you hear about the race between the lettuce and the tomato?{Environment.NewLine}A: The lettuce was a ""head"" and the tomato was trying to ""ketchup""! ",
      $@"Q: What is it called when a cat wins a dog show?{Environment.NewLine}A: A CAT-HAS-TROPHY! ",
      $@"Q: Why can't you give Elsa a balloon?{Environment.NewLine}A: Because she will Let it go. ",
      $@"Q: What do you get from a pampered cow?{Environment.NewLine}A: Spoiled milk. ",
      $@"Q: What do lawyers wear to court?{Environment.NewLine}A: Lawsuits! ",
      $@"Q: What gets wetter the more it dries?{Environment.NewLine}A: A towel. ",
      $@"Q: What do you get if you cross a cat with a dark horse?{Environment.NewLine}A: Kitty Perry ",
      $@"Q: What did the pencile say to the other pencil?{Environment.NewLine}A: your looking sharp. ",
      $@"Q: What did Bacon say to Tomato?{Environment.NewLine}A: Lettuce get together! ",
      $@"Q: What is the most hardworking part of the eye?{Environment.NewLine}A: the pupil ",
      $@"Q: How do you make a tissue dance?{Environment.NewLine}A: Put a little boogey in it! ",
      $@"Q: Why did the picture go to jail?{Environment.NewLine}A: Because it was framed. ",
      $@"Q: What do you call security guards working outside Samsung shops?{Environment.NewLine}A: Guardians of the Galaxy. ",
      $@"Q: What do you get when you cross fish and an elephant?{Environment.NewLine}A: Swimming trunks. ",
      $@"Q: Where do bees go to the bathroom?{Environment.NewLine}A: At the BP station! ",
      $@"Q: What do you call a baby monkey?{Environment.NewLine}A: A Chimp off the old block. ",
      $@"Q: Who earns a living driving their customers away?{Environment.NewLine}A: A taxi driver. ",
      $@"Q: ""How do you shoot a killer bee?""{Environment.NewLine}A: ""With a bee bee gun."" ",
      $@"Q: How do you drown a Hipster?{Environment.NewLine}A: In the mainstream. ",
      $@"Q: How do you make holy water?{Environment.NewLine}A: Boil the hell out of it! ",
      $@"Q: What happened to the dog that swallowed a firefly?{Environment.NewLine}A: It barked with de-light! ",
      $@"Q: What stays in the corner and travels all over the world?{Environment.NewLine}A: A stamp. ",
      $@"Q: Why did the computer go to the doctor?{Environment.NewLine}A: Because it had a virus! ",
      $@"Q: Why are frogs so happy?{Environment.NewLine}A: They eat whatever bugs them",
      $@"Q: What do you get when you cross a cow and a duck?{Environment.NewLine}A: Milk and quackers! ",
      $@"Q: What did the leopard say after eating his owner?{Environment.NewLine}A: Man, that hit the ""spot."" ",
      $@"Q: What do you call a sleeping bull?{Environment.NewLine}A: A bulldozer! ",
      $@"Q: What is the tallest building in the world?{Environment.NewLine}A: The library! It has the most stories! ",
      $@"Q: What do you call a belt with a watch on it?{Environment.NewLine}A: A waist of time ",
      $@"Q: Why did the banana go to the Doctor?{Environment.NewLine}A: Because it was not peeling well ",
      $@"Q: Why is England the wettest country?{Environment.NewLine}A: Because the queen has reigned there for years! ",
      $@"Q: Why do fish live in salt water?{Environment.NewLine}A: Because pepper makes them sneeze! ",
      $@"Q: Why did the man put his money in the freezer?{Environment.NewLine}A: He wanted cold hard cash! ",
      $@"Q: What do you get when you cross a snowman with a vampire?{Environment.NewLine}A: Frostbite. ",
      $@"Q: What is the best day to go to the beach?{Environment.NewLine}A: Sunday, of course! ",
      $@"Q: What bow can't be tied?{Environment.NewLine}A: A rainbow! ",
      $@"Q: What season is it when you are on a trampoline?{Environment.NewLine}A: Spring time. ",
      $@"Q: Where did the computer go to dance?{Environment.NewLine}A: To a disc-o. ",
      $@"Q: What has one head, one foot and four legs?{Environment.NewLine}A: A Bed ",
      $@"Q: What is the difference between a school teacher and a train?{Environment.NewLine}A: The teacher says spit your gum out and the train says ""chew chew chew"". ",
      $@"Q: Why did the birdie go to the hospital?{Environment.NewLine}A: To get a tweetment. ",
      $@"Q: What do you call someone who is afraid of Santa?{Environment.NewLine}A: A Clausterphobic ",
      $@"Q: What sound do porcupines make when they kiss?{Environment.NewLine}A: Ouch ",
      $@"Q: Why was the guy looking for fast food on his friend?{Environment.NewLine}A: Because his friend said dinner is on me. ",
      $@"Q: Why is a 2016 calendar more popular than a 2015 calendar?{Environment.NewLine}A: It has more dates. ",
      $@"Q: Did you hear the joke about the roof?{Environment.NewLine}A: Never mind, it's over your head! ",
      $@"Q: What is brown and has a head and a tail but no legs?{Environment.NewLine}A: A penny. ",
      $@"Q: Why didn't the skeleton go to the dance?{Environment.NewLine}A: Because he had no-body to go with. ",
      $@"Q: How do crazy people go through the forest?{Environment.NewLine}A: They take the psycho path. ",
      $@"Q: What three candies can you find in every school?{Environment.NewLine}A: Nerds, DumDums, and smarties. ",
      $@"Q: Why are pirates called pirates?{Environment.NewLine}A: Cause they arrrrr. ",
      $@"Q: What do prisoners use to call each other?{Environment.NewLine}A: Cell phones. ",
      $@"Q: Where do snowmen keep their money?{Environment.NewLine}A: In snow banks. ",
      $@"Q: What washes up on very small beaches?{Environment.NewLine}A: Microwaves!    ",
      $@"Q: What goes through towns, up & over hills, but doesn't move?{Environment.NewLine}A: The road! ",
      $@"Q: Why was there thunder and lightning in the lab?{Environment.NewLine}A: The scientists were brainstorming! ",
      $@"Q: Why did Tony go out with a prune?{Environment.NewLine}A: Because he couldn't find a date! ",
      $@"Q: What did the little mountain say to the big mountain?{Environment.NewLine}A: Hi Cliff! ",
      $@"Q: What did Winnie The Pooh say to his agent?{Environment.NewLine}A: Show me the honey! ",
      $@"Q: What do you call a funny mountain?{Environment.NewLine}A: hill-arious ",
      $@"Q: What did the candle say to the other candle?{Environment.NewLine}A: I'm going out tonight. ",
      $@"Q: Why couldn't the pirate play cards?{Environment.NewLine}A: Because he was sitting on the deck! ",
      $@"Q: What did the janitor say when he jumped out of the closet?{Environment.NewLine}A: (SUPPLIES!) ",
      $@"Q: Why did the traffic light turn red?{Environment.NewLine}A: You would too if you had to change in the middle of the street! ",
      $@"Q: What did one elevator say to the other elevator?{Environment.NewLine}A: I think I'm coming down with something! ",
      $@"Q: What do you say when you lose a wii game?{Environment.NewLine}A: I want a wii-match! ",
      $@"Q: What never asks questions but receives a lot of answers?{Environment.NewLine}A: the Telephone. ",
      $@"Q: How do you make an Octupus laugh?{Environment.NewLine}A: With ten-tickles ",
      $@"Q: Why can't your nose be 12 inches long?{Environment.NewLine}A: Because then it would be a foot! ",
      $@"Q: What has four wheels and flies?{Environment.NewLine}A: A garbage truck! ",
      $@"Q: What starts with a P, ends with an E, and has a million letters in it?{Environment.NewLine}A: Post Office! ",
      $@"Q: What did the blanket say to the bed?{Environment.NewLine}A: Don't worry, I've got you covered! ",
      $@"Q: Why should you take a pencil to bed?{Environment.NewLine}A: To draw the curtains! ",
      $@"Q: How many books can you put in an empty backpack?{Environment.NewLine}A: One! After that its not empty! ",
      $@"Q: What kind of flower doesn't sleep at night?{Environment.NewLine}A: The Day-zzz ",
      $@"Q: Did you hear they're changing the flooring in daycare centers?{Environment.NewLine}A: They're calling it infant-tile! ",
      $@"Q: What kind of button won't unbutton?{Environment.NewLine}A: A bellybutton! ",
      $@"Q: What did the triangle say to the circle?{Environment.NewLine}A: Your pointless! ",
      $@"Q: Why do sea-gulls fly over the sea?{Environment.NewLine}A: Because if they flew over the bay they would be bagels! ",
      $@"Q: What dog keeps the best time?{Environment.NewLine}A: A watch dog. ",
      $@"Q: What did the man say to the wall?{Environment.NewLine}A: One more crack like that and I'll plaster ya! ",
      $@"Q: Why did the tomato turn red?{Environment.NewLine}A: It saw the salad dressing! ",
      $@"Q: Why do girls scouts sell cookies?{Environment.NewLine}A: They wanna make a sweet first impression. ",
      $@"Q: What did the grape do when it got stepped on?{Environment.NewLine}A: It let out a little wine! ",
      $@"Q: What kind of berry has a coloring book?{Environment.NewLine}A: A crayon-berry ",
      $@"Q: What did the judge say when the skunk walked in the court room?{Environment.NewLine}A: Odor in the court. ",
      $@"Q: What did the fish say when he swam into the wall?{Environment.NewLine}A: Dam! ",
      $@"Q: Why don't skeletons fight each other?{Environment.NewLine}A: They don't have the guts. ",
      $@"Q: What did the janitor say when he jumped out of the closet?{Environment.NewLine}A: SUPPLIES! ",
      $@"Q: Why did the scientist go to the tanning salon?{Environment.NewLine}A: Because he was a paleontologist. ",
      $@"Q: What happened when a faucet, a tomato and lettuce were in a race?{Environment.NewLine}A: The lettuce was ahead, the faucet was running and the tomato was trying to ketchup. ",
      $@"Q: Why was the student's report card wet?{Environment.NewLine}A: It was below C level! ",
      $@"Q: How many tickles does it take to make an octopus laugh?{Environment.NewLine}A: Tentacles. ",
      $@"Q: What did the traffic light say to the car?{Environment.NewLine}A: Don't look, I'm changing. ",
      $@"Q: What do you call cheese that is not yours?{Environment.NewLine}A: Nacho Cheese ",
      $@"Q: How do you find a Princess?{Environment.NewLine}A: You follow the foot Prince. ",
      $@"Q: What streets do ghosts haunt?{Environment.NewLine}A: Dead ends! ",
      $@"Q: What did the penny say to the other penny?{Environment.NewLine}A: We make perfect cents. ",
      $@"Q: Why did the man with one hand cross the road?{Environment.NewLine}A: To get to the second hand shop. ",
      $@"Q: Why did the boy sprinkle sugar on his pillow before he went to sleep?{Environment.NewLine}A: So he could have sweet dreams. ",
      $@"Q: Why did the robber take a bath?{Environment.NewLine}A: Because he wanted to make a clean getaway. ",
      $@"Q: What happens if life gives you melons?{Environment.NewLine}A: Your dyslexic ",
      $@"Q: What music are balloons scared of?{Environment.NewLine}A: Pop music ",
      $@"Q: What did the judge say to the dentist?{Environment.NewLine}A: Do you swear to pull the tooth, the whole tooth and nothing but the tooth. ",
      $@"Q: Why did the boy tiptoe past the medicine cabinet?{Environment.NewLine}A: He didn't want to wake the sleeping pills! ",
      $@"Q: What do you get when you cross a fridge with a radio?{Environment.NewLine}A: Cool Music. ",
      $@"Q: What goes up when the rain comes down?{Environment.NewLine}A: An umbrella. ",
      $@"Q: Why did the belt go to jail?{Environment.NewLine}A: Because it held up a pair of pants! ",
      $@"Q: What happens if life gives you melons?{Environment.NewLine}A: Your dyslexic ",
      $@"Q: What did the stamp say to the envelope?{Environment.NewLine}A: Stick with me and we will go places! ",
      $@"Q: What kind of lights did Noah use on the Ark?{Environment.NewLine}A: Flood lights! ",
      $@"Q: Why don't you see giraffes in elementary school?{Environment.NewLine}A: Because they're all in High School! ",
      $@"Q: Which is the longest word in the dictionary?{Environment.NewLine}A: ""Smiles"", because there is a mile between each ""s""! ",
      $@"Q: Which month do soldiers hate most?{Environment.NewLine}A: The month of March! ",
      $@"Q: What did the painter say to the wall?{Environment.NewLine}A: One more crack like that and I'll plaster you! ",
      $@"Q: Why did the computer break up with the internet?{Environment.NewLine}A: There was no ""Connection"". ",
      $@"Q: Why do golfers wear two pairs of pants?{Environment.NewLine}A: In case they get a hole in one! ",
      $@"Q: Why can't you take a nap during a race?{Environment.NewLine}A: Because if you snooze, you loose! ",
      $@"Q: Why did Goofy put a clock under his desk?{Environment.NewLine}A: Because he wanted to work over-time! ",
      $@"Q: Why did Johnny throw the clock out of the window?{Environment.NewLine}A: Because he wanted to see time fly! ",
      $@"Q: What do you call a book that's about the brain?{Environment.NewLine}A: A mind reader. ",
      $@"Q: When do you stop at green and go at red?{Environment.NewLine}A: When you're eating a watermelon! ",
      $@"Q: Why did God make only one Yogi Bear?{Environment.NewLine}A: Because when he tried to make a second one he made a Boo-Boo ",
      $@"Q: How did the farmer mend his pants?{Environment.NewLine}A: With cabbage patches! ",
      $@"Q: Why did the man lose his job at the orange juice factory?{Environment.NewLine}A: He couldn't concentrate! ",
      $@"Q: How do you repair a broken tomato?{Environment.NewLine}A: Tomato Paste! ",
      $@"Q: Why did the baby strawberry cry?{Environment.NewLine}A: Because his parents were in a jam! ",
      $@"Q: What was the Cat in the Hat looking for in the toilet?{Environment.NewLine}A: For thing one and thing two. ",
      $@"Q: What did the hamburger name his daughter?{Environment.NewLine}A: Patty! ",
      $@"Q: What kind of egg did the bad chicken lay?{Environment.NewLine}A: A deviled egg! ",
      $@"Q: What kind of key opens the door on Thanksgiving?{Environment.NewLine}A: A turkey! ",
      $@"Q: Why did the cookie go to the hospital?{Environment.NewLine}A: He felt crummy! ",
      $@"Q: Why were the teacher's eyes crossed?{Environment.NewLine}A: She couldn't control her pupils! ",
      $@"Q: What do you call a guy who never farts in public?{Environment.NewLine}A: A private tutor. ",
      $@"Q: What do you call a bear with no socks on?{Environment.NewLine}A: Bare-foot. ",
      $@"Q: What can you serve but never eat?{Environment.NewLine}A: A volleyball. ",
      $@"Q: What kind of shoes do all spies wear?{Environment.NewLine}A: Sneakers. ",
      $@"Q: Why did the soccer player bring string to the game?{Environment.NewLine}A: So he could tie the score. ",
      $@"Q: Why is a baseball team similar to a muffin?{Environment.NewLine}A: They both depend on the batter. ",
      $@"Q: What did the alien say to the garden?{Environment.NewLine}A: Take me to your weeder. ",
      $@"Q: Why do watermelons have fancy weddings?{Environment.NewLine}A: Because they cantaloupe. ",
      $@"Q: Have you heard the joke about the butter?{Environment.NewLine}A: I better not tell you, it might spread. ",
      $@"Q: How do baseball players stay cool?{Environment.NewLine}A: They sit next to their fans. ",
      $@"Q: Why was the math book sad?{Environment.NewLine}A: Because it had too many problems. ",
      $@"Q: What runs but doesn't get anywhere?{Environment.NewLine}A: A refrigerator. ",
      $@"Q: What is an astronaut's favorite place on a computer?{Environment.NewLine}A: The Space bar! ",
      $@"Q: What exam do young witches have to pass?{Environment.NewLine}A: A spell-ing test! ",
      $@"Q: What do you call a sheep with no head and no legs?{Environment.NewLine}A: A cloud! ",
      $@"Q: Why did the boy eat his homework?{Environment.NewLine}A: Because his teacher said it was a piece of cake! ",
      $@"Q: Why is Basketball such a messy sport?{Environment.NewLine}A: Because you dribble on the floor! ",
      $@"Q: How do you communicate with a fish?{Environment.NewLine}A: Drop him a line! ",
      $@"Q: Where do sheep go to get haircuts?{Environment.NewLine}A: To the Baa Baa shop! ",
      $@"Q: What does a shark like to eat with peanut butter?{Environment.NewLine}A: Jellyfish! ",
      $@"Q: What do cats eat for breakfast?{Environment.NewLine}A: Mice Crispies! ",
      $@"Q: Who goes to the bathroom in the middle of a party?{Environment.NewLine}A: A party pooper. ",
      $@"Q: Why can't a leopard hide?{Environment.NewLine}A: Because he's always spotted! ",
      $@"Q: What do you give a dog with a fever?{Environment.NewLine}A: Mustard, its the best thing for a hot dog! ",
      $@"Q: What do you get when you cross a cat with a lemon?{Environment.NewLine}A: A sour puss! ",
      $@"Q: Why do birds fly south for the winter?{Environment.NewLine}A: Its easier than walking! ",
      $@"Q: What did the M&M go to college?{Environment.NewLine}A: Because he wanted to be a Smarty. ",
      $@"Q: What kind of key opens a banana?{Environment.NewLine}A: A monkey! ",
      $@"Q: How do you know that carrots are good for your eyesight?{Environment.NewLine}A: Have you ever seen a rabbit wearing glasses? ",
      $@"Q: Why does a hummingbird hum?{Environment.NewLine}A: It doesn't know the words! ",
      $@"Q: What do you call a house that likes food?{Environment.NewLine}A: a Condoment! ",
      $@"Q: Why are some fish at the bottom of the ocean?{Environment.NewLine}A: Because they dropped out of school! ",
      $@"Q: What do you call a pile of kittens{Environment.NewLine}A: a meowntain ",
      $@"Q: What goes up and down but doesn't move?{Environment.NewLine}A: The temperature! ",
      $@"Q: What happened to the wooden car with wooden wheels and wooden engine?{Environment.NewLine}A: it wooden go! ",
      $@"Q: Which weighs more, a ton of feathers or a ton of bricks?{Environment.NewLine}A: Neither, they both weigh a ton! ",
      $@"Q: What has one horn and gives milk{Environment.NewLine}A: A milk truck. Q. Did you hear about the party a little boy had for his sisters barbie dolls? A. It was a Barbie-Q. ",
      $@"Q: Where do bulls get their messages?{Environment.NewLine}A: On a bull-etin board. ",
      $@"Q: What do bulls do when they go shopping?{Environment.NewLine}A: They CHARGE! ",
      $@"Q: What runs but can't walk?{Environment.NewLine}A: The faucet! ",
      $@"Q: Whens the best time to go to the dentist?{Environment.NewLine}A: Tooth-hurty ",
      $@"Q: What kind of bed does a mermaid sleep in?{Environment.NewLine}A: A water bed! ",
      $@"Q: What kind of crackers do firemen like in their soup?{Environment.NewLine}A: Firecrackers! ",
      $@"Q: Why did the barber win the race?{Environment.NewLine}A: Because he took a short cut. ",
      $@"Q: What's taken before you get it?{Environment.NewLine}A: Your picture. ",
      $@"Q: What concert costs 45 cents?{Environment.NewLine}A: 50 Cent featuring Nickleback. ",
      $@"Q: Why did the tree go to the dentist?{Environment.NewLine}A: To get a root canal. ",
      $@"Q: When I was young there was only 25 letters in the Alphabet?{Environment.NewLine}A: Nobody new why. ",
      $@"Q: What is it called when a cat wins a dog show?{Environment.NewLine}A: A CAT-HAS-TROPHY! ",
      $@"Q: What can go up a chimney down, but can't go down a chimney up?{Environment.NewLine}A: An umbrella. ",
      $@"Q: Why was the broom late?{Environment.NewLine}A: It over swept! ",
      $@"Q: Why didn't the 11 year old go to the pirate movie?{Environment.NewLine}A: because it was rated arrrrr",
      $@"Q: What did the Super Nintendo say to the Sega Genesis?{Environment.NewLine}A: ""You know, everyone always tells me that I'm a bit better than you."" ",
      $@"Q: What's the difference between Ms. and Mrs.?{Environment.NewLine}A: Mr. ",
      $@"Q: What word looks the same backwards and upside down?{Environment.NewLine}A: Swims ",
      $@"Q: Where does a tree store their stuff?{Environment.NewLine}A: In there Trunk! ",
      $@"Q: What did the nose say to the finger?{Environment.NewLine}A: Stop picking on me. ",
      $@"Q: What did the tie say to the hat?{Environment.NewLine}A: You go on ahead and I'll hang around! ",
      $@"Q: Where does bad light go?{Environment.NewLine}A: PRISM! ",
      $@"Q: What did one plate say to the other?{Environment.NewLine}A: Dinners on me ",
      $@"Q: Who cleans the bottom of the ocean?{Environment.NewLine}A: A Mer-Maid ",
      $@"Q: Where do pencils go on vacation?{Environment.NewLine}A: Pennsylvania ",
      $@"Q: What is heavy forward but not backward?{Environment.NewLine}A: Ton. ",
      $@"Q: What do you get when you plant kisses?{Environment.NewLine}A: Tu-lips (two-lips) ",
      $@"Q: What pet makes the loudest noise?{Environment.NewLine}A: A trum-pet! ",
      $@"Q: What do you call a rabbit with fleas?{Environment.NewLine}A: Bugs Bunny! ",
      $@"Q: Why did the girl bring lipstick and eye shadow to school?{Environment.NewLine}A: She had a make-up exam! ",
      $@"Q: What is a bubbles least favorite drink?{Environment.NewLine}A: Soda POP ",
      $@"Q: What did one eyeball say to the other eyeball?{Environment.NewLine}A: Between you and me something smells. ",
      $@"Q: What stays on the ground but never gets dirty?{Environment.NewLine}A: Shadow. ",
      $@"Q: Name a city where no one goes?{Environment.NewLine}A: Electricity ",
      $@"Q: What four letters will frighten a burglar?{Environment.NewLine}A: O I C U ",
      $@"Q: What's the difference between a cat and a frog?{Environment.NewLine}A: A Cat has nine lives but a Frog croaks every night! ",
      $@"Q: Why can you never trust atoms?{Environment.NewLine}A: They make up everything! ",
      $@"Q: Where does bad light go?{Environment.NewLine}A: To prism! ",
      $@"Q: I can run but not walk, have a mouth but can't talk, and a bed, but I do not sleep. What am I?{Environment.NewLine}A: A River."
    };

    public static string Get(int indent = 0, Random random = null)
    {
      var joke = GetJoke(random ?? new Random());

      var lines = joke.Split(new[] { Environment.NewLine }, StringSplitOptions.None);

      var indentText = String.Concat(BuildIndentText(indent));

      return string
        .Join(Environment.NewLine, lines.Select(line => $"{indentText}{line}"))
        .TrimStart(Environment.NewLine.ToCharArray());
    }

    private static IEnumerable<char> BuildIndentText(int indent)
    {
      for (var i = 0; i < indent; i++)
      {
        yield return ' ';
      }
    }

    private static string GetJoke(Random random = null)
    {
      var index = random.Next(0, jokes.Count());

      return jokes[index];
    }
  }
}
